### PR TITLE
1. fix conflicts between gudstrap and Etown.

### PR DESCRIPTION
**Pull request by phariel**
1. fix grunt test procedure error.

### CODE REVIEW

**Comment by normanzb** [comment]
oops? no umd header? how do we use it in amd module then?

**Comment by normanzb** [comment]
especially when in multiple jquery env, you will end up attaching it to the default jQuery.fn

with umd header you can override the package name in require js config to make it attach to the right one.

**Comment by phariel** [comment]
I'm wondering how would you resolve shadow mode issue with double `define` ?

**Comment by normanzb** [comment]
would u mind elaboration?
i dont know what is double define. i can see only one.

**Pull request merged**
