### PR TITLE
Add Standard Toggles

### PR DESCRIPTION
**Pull request by phariel**
#### Add standard toggles.

Preview: http://phariel.github.io/ef-bootstrap/components-ef/

TODO: I'll continue to refine this part.

### CODE REVIEW

**Comment by chrometaphore** [comment]
Great job on this. 
My suggestions:
1 - the component button should be draggable as well to change state 
2 - When we have this component with labels, the component should not change size when the state is changed (so i guess we have to calculate the size using the side with the longer label to avoid this)

**Comment by phariel** [comment]
@chrometaphore Yes of cause,  this's the action item which need to be done later.
1. For draggable toggle, I'll add mouse drag event for desktop and touch event for iOS.
2. For width of label, I suggest that adding several different width classes (eg: .sdtoggle-label-small, .sdtoggle-label-medium, .sdtoggle-label-large) instead of calculate width by javascript automatically. Therefore, we could keep our style format consistently.

**Comment by phariel** [comment]
@faceach @normanzb @mikaelkaron 
You could review this pull request.
If passed, merge it by someone or inform me to merge.

**Comment by jacksky007** [comment]
There are some little issues and some my thoughts.
- I think we'd better separate html with js. The labels are now hard coded is js.
- The widths are different while toggling.
- Should we rename the js file with '-ef'?

I also suggest codes like this

``` javascript
if ($this.data(sdtoggleBase)) {
  setToggle($this, false)
} else {
  setToggle($this, true)
}
```

written in this way

``` javascript
setToggle($this, !$this.data(sdtoggleBase))
```

**Comment by mikaelkaron** [comment]
I have some comments on the js, but before that I'd like @normanzb or @faceach to take a look at the general structure of the css/less and the packaging (are we putting the files in the right place etc.).

I also agree with @jacksky007 abobove on separating js/html and file naming (I think, again I'd defer to someone from the front-end group to decide on this)

**Comment by phariel** [comment]
Guys, I should close this pull request and make codes better, sorry for any inconvenience

**Comment by faceach** [comment]
@phariel , about the name "sdtoggle", what is "sd" means? And I saw an inset box-shadow when hover the toggle button, please check!

**Comment by phariel** [comment]
@faceach "sd" means "standard", I wanna make this word shorter.
About box-shadow, I didn't add any shadow on it, it just turn to :hover style when hover it, please re-check.

**Comment by faceach** [comment]
@phariel we can remove sd from class name, just follow other components; and the hover box-shadow, could you remove it, because CODA design is a pure flat UI, no shadow anymore:)

**Comment by chrometaphore** [comment]
Alternatively, we could use 'std' as a common shortened version of 'standard' :)

**Comment by phariel** [comment]
@faceach what does box-shadow mean? I did NOT add any box-shadow style on it, and the :HOVER style is consistent with normal button CSS definition

**Comment by phariel** [comment]
@faceach do you mean when pressing toggle button with left-click, the inner button shows a box-shadow? It's a default button active style in .btn:active of buttons.less, you can see it on any button when pressing. If we don't want see this style, I'll create a new style class for toggle, or we remove box-shadow in .btn:active of buttons.less for ALL BUTTONS.

**Comment by phariel** [comment]
@faceach @chrometaphore for class name of standard toggle, I'll use `.toggle` directly, but we must avoid using `.toggle` class in other components coding.

**Comment by phariel** [comment]
@jacksky007 about width of label, I suggested:

> For width of label, I suggest that adding several different width classes (eg: .toggle-label-small, .toggle-label-medium, .toggle-label-large) instead of calculate width by javascript automatically. Therefore, we could keep our style format consistently.

@jacksky007 @mikaelkaron about separate html with js, I'll add `data-label-on` and `data-label-off` attributes on toggle element for custom i18n label text. Hardcoding 'ON' and 'OFF' are default text without these 2 attributes. Is this okay or not?

**Comment by faceach** [comment]
@phariel Remove box-shadow in .btn:active will be better, I will create another issue for this, thank you!

**Comment by mikaelkaron** [comment]
I like pulling all 'translatable' text into attributes, this is a lot easier from a i18n point of view, btw, this _also_ goes for any widget that needs to format numbers/dates to, we need to be prepared here to.

**Pull request closed without merging**
